### ISSUE TITLE
First attempt at skyline run

### ISSUE THREAD

**Issue by ArtPoon** [ArtPoon/BelleJS#15]
```
Creating the tree model, 'treeModel'
  taxon count = 71
  tree height = 152.9034811119163
Bayesian skyline plot: 50 linear control points
Fatal exception: Dimension of population parameter must be one greater than dimension of group size parameter.
java.lang.IllegalArgumentException: Dimension of population parameter must be one greater than dimension of group size parameter.
	at dr.evomodel.coalescent.BayesianSkylineLikelihood.<init>(Unknown Source)
	at dr.evomodelxml.coalescent.BayesianSkylineLikelihoodParser.parseXMLObject(Unknown Source)
	at dr.xml.AbstractXMLObjectParser.parseXMLObject(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.parse(Unknown Source)
	at dr.app.beast.BeastMain.<init>(Unknown Source)
	at dr.app.beast.BeastMain.main(Unknown Source)
```

**Comment by GopiGugan** [comment]
I though population parameter must be one greater than the group size only for "Piecewise-linear" skyline model?

**Comment by ArtPoon** [comment]
This is the BEAUti version:
```xml
	<!-- Generate a generalizedSkyLineLikelihood for Bayesian Skyline            -->
	<generalizedSkyLineLikelihood id="skyline" linear="false">
		<populationSizes>
			<parameter id="skyline.popSize" dimension="50" value="1.0" lower="0.0"/>
		</populationSizes>
		<groupSizes>
			<parameter id="skyline.groupSize" dimension="50"/>
		</groupSizes>
		<populationTree>
			<treeModel idref="treeModel"/>
		</populationTree>
	</generalizedSkyLineLikelihood>
	
	<exponentialMarkovLikelihood id="eml1" jeffreys="true">
		<chainParameter>
			<parameter idref="skyline.popSize"/>
		</chainParameter>
	</exponentialMarkovLikelihood>
```

This is Belle:
```xml

	<!-- Generate a coalescent likelihood                                        -->
	<generalizedSkyLineLikelihood id="skyline" linear="true">
  <populationSizes>
    <parameter id="skyline.popSize" dimension="50" value="1.0" lower="0.0"/>
  </populationSizes>
  <groupSizes>
    <parameter id="skyline.groupSize" dimension="50"/>
  </groupSizes>
  <populationTree>
    <treeModel idref="treeModel"/>
  </populationTree>
</generalizedSkyLineLikelihood><exponentialMarkovLikelihood id="eml1" jeffreys="true">
  <chainParameter>
    <parameter idref="skyline.popSize"/>
  </chainParameter>
</exponentialMarkovLikelihood>
```

**Comment by ArtPoon** [comment]
Ah I have BEAUti set to piecewise constant - we should do the same as default, i.e., disable piecewise linear

**Comment by ArtPoon** [comment]
Manually edited Belle XML for now to set `linear=false`.
New error:
```
Using TreeDataLikelihood
  Branch rate model used: discretizedBranchRates
Optimization Schedule: default
Mar 30, 2021 10:34:13 PM dr.app.beast.BeastMain <init>
SEVERE: Parsing error - poorly formed BEAST file, belle-hky-ucln-skyline.xml:
Object with idref=coalescent has not been previously declared.

Error thrown at: dr.xml.XMLParser.convert(Unknown Source)
```

**Comment by ArtPoon** [comment]
BEAUti `<prior>` block:
```xml
			<prior id="prior">
				<logNormalPrior mu="1.0" sigma="1.25" offset="0.0">
					<parameter idref="kappa"/>
				</logNormalPrior>
				<dirichletPrior alpha="1.0" sumsTo="1.0">
					<parameter idref="frequencies"/>
				</dirichletPrior>
				<ctmcScalePrior>
					<ctmcScale>
						<parameter idref="ucld.mean"/>
					</ctmcScale>
					<treeModel idref="treeModel"/>
				</ctmcScalePrior>
				<exponentialPrior mean="0.3333333333333333" offset="0.0">
					<parameter idref="ucld.stdev"/>
				</exponentialPrior>
				<uniformPrior lower="0.0" upper="1.0E100">
					<parameter idref="skyline.popSize"/>
				</uniformPrior>
				<generalizedSkyLineLikelihood idref="skyline"/>
				<exponentialMarkovLikelihood idref="eml1"/>
				
				
				<discretizedBranchRates idref="branchRates"/>
			</prior>
```

Belle (with a bit of whitespace reformatting):
```xml
			<prior id="prior">
				<logNormalPrior mu="1.0" sigma="1.25" offset="0.0">
					<parameter idref="kappa"/>
				</logNormalPrior>
				<coalescentLikelihood idref="coalescent"/>
			<ctmcScalePrior>
  <ctmcScale>
    <parameter idref="ucld.mean"/>
  </ctmcScale>
  <treeModel idref="treeModel"/>
</ctmcScalePrior>
<exponentialPrior mean="0.333333" offset="0">
<parameter idref="ucld.stdev"/>
</exponentialPrior>
<uniformPrior lower="0" upper="1e+100">
<parameter idref="skyline.popSize"/>
</uniformPrior>
<discretizedBranchRates idref="branchRates"/>
</prior>
```

**Comment by ArtPoon** [comment]
Hm, Dirichlet prior for `frequencies` is missing, and we have an extra `coalescentLikelihood`.

**Comment by ArtPoon** [comment]
Probably  need to replace `coalescentLikelihood` with these:
```xml
<generalizedSkyLineLikelihood idref="skyline"/>
				<exponentialMarkovLikelihood idref="eml1"/>
```

**Comment by ArtPoon** [comment]
I'm turning off piecewise linear in index

**Comment by ArtPoon** [comment]
`xmlWriter.js`:
```js
      let piecewise_linear = $("#select-skyline").val()==="skylinePWConst",
          generalizedSkyline= xmlReader.parseFromString(`
<generalizedSkyLineLikelihood id="skyline" linear="${piecewise_linear}">
```

**Comment by ArtPoon** [comment]
Separated skyline/coalescent likelihood code from starting tree function

**Comment by ArtPoon** [comment]
New problem:
```
Mar 30, 2021 11:07:14 PM dr.app.beast.BeastMain <init>
SEVERE: Parsing error - poorly formed BEAST file, belle-hky-ucln-skyline.xml:
Object with idref=constant has not been previously declared.
```

**Comment by ArtPoon** [comment]
Still need to eliminate this:
```xml
	<!-- Generate a coalescent likelihood                                        -->
	<coalescentLikelihood id="coalescent">
		<model>
			<constantSize idref="constant"/>
		</model>
		<populationTree>
			<treeModel idref="treeModel"/>
		</populationTree>
	</coalescentLikelihood>
```

**Comment by GopiGugan** [comment]
Isn't the above block only generated when Tree Prior is set to "Coalescent: Constant Size"?

**Comment by ArtPoon** [comment]
I guess it's in the template XML

**Comment by ArtPoon** [comment]
Argh, coalescent likelihood is still in the logs
```
Likelihood computation is using an auto sizing thread pool.
Mar 30, 2021 11:37:21 PM dr.app.beast.BeastMain <init>
SEVERE: Parsing error - poorly formed BEAST file, belle-hky-ucln-skyline.xml:
Object with idref=coalescent has not been previously declared.
```
